name: Deployment Workflow

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set Deployment Environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
          else
            echo "DEPLOY_ENV=unknown" >> $GITHUB_ENV

      - name: Log Deployment Environment
        run: echo "Deployment Environment:${{ env.DEPLOY_ENV }}"

      - name: Simulate Deployment
        run: echo "Deploying to ${{ env.DEPLOY_ENV }} environment"
