name: Deployment Workflow

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Deployment Environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "DEPLOY_ENV=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV

      - name: Log Deployment Environment
        run: echo "Deployment Environment:$DEPLOY_ENV"

      - name: Simulate Deployment
        run: echo "Deploying to $env.DEPLOY_ENV environment"
