name: Matrix Context

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Print matrix properties
        run: |
          echo "Node version: ${{ matrix.node }}"
          echo "Operating system: ${{ matrix.os }}"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
