name: Needs Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run build
        run: echo "Building project..."
        id: build_step

      - name: Set build output
        run: echo "::set-output name=build_output::Build completed"
        id: set_output

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print build output
        run: echo "Build output: ${{ needs.build.outputs.build_output }}"

      - name: Run tests
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print build and test results
        run: |
          echo "Build result: ${{ needs.build.result }}"
          echo "Test result: ${{ needs.test.result }}"

      - name: Deploy application
        run: echo "Deploying application..."
