name: Secret Context

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print GitHub token
        run: echo "GITHUB_TOKEN:${{ secrets.GITHUB_TOKEN }}"

      - name: Use custom secret
        run: echo "MY_SECRET:${{ secrets.MY_SECRET }}"
